### ISSUE TITLE
train was killed

### ISSUE THREAD

**Issue by xiaoxinning** [ExplainableML/TCAF-GZSL#13]
i have a question when I use this command
python3 main.py --cfg /root/autodl-tmp/TCAF-GZSL/config/best/best_cls/best_anet.yaml  --root_dir avgzsl_benchmark_non_averaged_datasets/UCF --log_dir networks/activitynet_cls --dataset_name ActivityNet --run all

it turns out that my program was killed because memory is full even 80G.it just don't use GPU's memory at all

**Comment by MerceaOtniel** [comment]
I do not understand. Was your previous error due to a different numpy library? Did you fix that? If so, then please respond so that we can close that issue.

And afterwards you get the memory issue? All these datasets are loaded in RAM and then, the batches are loaded in GPU memory. You get this error because the RAM memory is probably full. You need around 80GB RAM if i remember correctly for ActivityNet, and much less for the other 2 datasets, as we load all the features in memory at once. ActivityNet has long videos, which consumes a lot of memory. We are aware of this issue, but for our setup when we did the project, it was desirable to load everything in memory. However, you can try to change this if it is not suitable for you.
